# Generated by Django 3.0.4 on 2021-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('news_text', models.TextField(verbose_name='Основной текст')),
                ('news_dates', models.TextField(verbose_name='Даты проведения')),
                ('news_image', models.ImageField(upload_to='images/', verbose_name='Превью')),
            ],
        ),
    ]
